@startuml
left to right direction
actor "admine" as fc
rectangle reservations {
  usecase "Accepter la demande" as UC1
  usecase "Modifier la demande" as UC2
  usecase "Annuler la demande" as UC3
}
actor "client" as gc
rectangle service{
  usecase "Réserve le service" as UC4
  usecase "Choisir le temps" as UC5
  usecase "Annuler la réservation" as UC6
}
fc -- UC1
fc -- UC2
fc -- UC3
gc -- UC4
gc -- UC5
gc -- UC6
@enduml
